---
Métricas de Grafos - R
---
```{r}
#install.packages("igraph")
library(igraph)
```
Métricas
```{r}
#Carregamos um grafo de relacionamentos de 53 vértices e 179 arestas
grafo8 = read_graph("Grafo.graphml", format = c("graphml"))
#53 vertices e 179 arestas
grafo8
plot(grafo8)
#grau de entraida e saida
degree(grafo8, mode = "all")
#entrada
degree(grafo8, mode = "in")
#saida
degree(grafo8, mode = "out")

#colocando o grau no tamanho do vértice
grau = degree(grafo8, mode = "in")
plot(grafo8, vertex.size=grau)
```
Mais métricas
```{r}
#diametro (maior distância entre diferentes vértices)
diameter(grafo8, directed = T)
diameter(grafo8, directed = F)

#vertices que formam o diametro
get_diameter(grafo8, directed = T)
get_diameter(grafo8, directed = F)
```
Mais métricas
```{r}
#vizinhança, zero incluio o próprio vertice, mode all não considera a direção
neighborhood(grafo8, 0, mode = c("all"))

#densidade do grafo
edge_density(grafo8)

#teste de isomorfismo
grafo9 = grafo8
isomorphic(grafo8, grafo9)
```

